"""Core domain model, events, projections."""

from records.core.dispatch import (
    EVENT_FREE_DOC_TYPES,
    event_for_fields,
    has_event_vocabulary,
)
from records.core.event_log import DomainEvent, append, replay
from records.core.linking import (
    AMBIGUOUS,
    LINKED,
    NEW_ENTITY,
    NO_IDENTIFIERS,
    NO_MATCH,
    LinkResult,
    known_entities,
    link_document,
)
from records.core.projections import (
    conflicting_policy_filed,
    current_policies,
    renewal_calendar,
    renewal_offers,
)
from records.core.model import (
    RENEWAL_ALREADY_ACCEPTED,
    RENEWAL_PROPOSED,
    Decision,
    DocTypeVerdict,
    DocumentDiscarded,
    Extraction,
    Field,
    FieldExtraction,
    NcdConfirmed,
    PolicyCorrected,
    PolicyFiled,
    ProductLine,
    RenewalAccepted,
    RenewalProposed,
    Shape,
    extraction_from_dict,
    field_extraction_from_dict,
)
from records.core.registry import (
    FACT_SOURCE,
    PROOF_ARTIFACT,
    RAW_EVIDENCE,
    REFERENCE_TEXT,
    REGISTRY,
    ROLES,
    UNKNOWN_DOC_TYPE,
    DocTypeSchema,
)
from records.core.trust import (
    TRUST_EXTRACTED,
    TRUST_INTERPRETED,
    TRUST_VERIFIED,
    min_trust,
)

__all__ = [
    "AMBIGUOUS",
    "EVENT_FREE_DOC_TYPES",
    "LINKED",
    "NEW_ENTITY",
    "NO_IDENTIFIERS",
    "NO_MATCH",
    "LinkResult",
    "known_entities",
    "link_document",
    "FACT_SOURCE",
    "PROOF_ARTIFACT",
    "RAW_EVIDENCE",
    "REFERENCE_TEXT",
    "REGISTRY",
    "RENEWAL_ALREADY_ACCEPTED",
    "RENEWAL_PROPOSED",
    "ROLES",
    "TRUST_EXTRACTED",
    "TRUST_INTERPRETED",
    "TRUST_VERIFIED",
    "UNKNOWN_DOC_TYPE",
    "min_trust",
    "DocTypeSchema",
    "DocTypeVerdict",
    "DocumentDiscarded",
    "DomainEvent",
    "NcdConfirmed",
    "PolicyCorrected",
    "PolicyFiled",
    "append",
    "replay",
    "conflicting_policy_filed",
    "current_policies",
    "event_for_fields",
    "has_event_vocabulary",
    "renewal_calendar",
    "renewal_offers",
    "extraction_from_dict",
    "field_extraction_from_dict",
    "Decision",
    "Extraction",
    "Field",
    "FieldExtraction",
    "ProductLine",
    "RenewalAccepted",
    "RenewalProposed",
    "Shape",
]
